### ISSUE TITLE
Jimp does not provide export named 'default' error

### ISSUE THREAD

**Issue by papaformigas** [sprintermax/FNItemShopGenerator#2] opened 2024-12-08 01:03 UTC
Getting this error always...
 any solution? thanks!

C:\Fortnite\FNItemShopGenerator-main>node index_fn-api.com.js
file:///C:/Fortnite/FNItemShopGenerator-main/index_fn-api.com.js:4
import Jimp from "jimp";
       ^^^^
SyntaxError: The requested module 'jimp' does not provide an export named 'default'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:177:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:260:5)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:543:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:116:5)

Node.js v23.1.0

C:\Fortnite\FNItemShopGenerator-main>pause
Press any key to continue . . .

**Comment by sprintermax** [comment] 2024-12-08 18:22
Hi, I tried to reproduce the same error but with no success... Everything worked fine and as expected here.

Did you checked your node installation, if so, already tried reinstalling it?
Have you followed the steps on the readme and the Jimp version is 0.16.x? (can be verified by running `npm list` on the project directory)

Also, did you made any changes to the .js program files?

**Comment by papaformigas** [comment] 2024-12-08 22:07
Hi,

Your script was working fine, but after the Fortnite API changed the JSON formatting, the script stopped working correctly and has been throwing errors since.

Here is the log from npm list:

node:24484) ExperimentalWarning: CommonJS module C:\Users\lo\AppData\Roaming\npm\node_modules\npm\node_modules\debug\src\node.js is loading ES Module C:\Users\lo\AppData\Roaming\npm\node_modules\npm\node_modules\supports-color\index.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
fnitemshopgenerator@1.0.0 C:\Fortnite\FNItemShopGenerator-main
+-- discord-webhook-node@1.1.8
+-- dotenv@16.4.5
+-- jimp@1.6.0
+-- node-fetch@3.3.2
`-- twitter-api-v2@1.18.1

I didnt change the js files.

**Comment by sprintermax** [comment] 2024-12-08 22:15
Ooh, I see the problem, it's not on the API... Somehow you updated your Jimp package to v1.6, the project needs to use an older version v0.16 because was made a long time ago... that's why it is conflicting and not working...

Just delete the project folder and redownload, setup it following the instructions and you should be fine

**Comment by papaformigas** [comment] 2024-12-08 22:34
Got it! It does work now... the Fortniteapi.io version craetes a massive file with jasmtracks and cosmetics, would be cool to generate two seprate images opne from the trackls and the other from the cosmetics. this is only a suggestion. 

Now can this script send the image to twitter ? How can i also send it to discord? and how can i setup the bat file to run at shop rotation autromaticxaly everyday on windows, tweet the image and send it to discord?

**Comment by sprintermax** [comment] 2024-12-08 23:08
Hi, great that you were able to fix the issue!

About the sorting and filtering, it's possible but will require some knowledge of javascript to change how it works... It has already some jamtracks filtering that I made quickly by other requests, but I really can't keep updating it a lot to add many requests, sorry...

This was made a long time ago, I made minimal changes to support new api formats, but I am unsure if the discord/github api still works... And I did not made integration to send on twitter, you may have to do your own research if you want to modify it to be able to do it...

To run automatically, may need external resources such as timed scripts and extra verification to avoid duplicated shops (comparing hashes). That is also a thing you must search by yourself, since the script provided does not handle it...

I am closing this issue since its original topic was fixed :V

**Closed as completed by sprintermax** 2024-12-08 23:08 UTC
